### PR TITLE
Rating an accomodation

### PR DESCRIPTION
**Pull request by pmuhire**

### CODE REVIEW

**Review by nbrucepro — APPROVED** [review]

**Review by leny62 — CHANGES_REQUESTED** [review]
Nice job @pmuhire , but please increase your test coverage please.
Merging your PR will reduce the whole project's test coverage by a big value

**Comment by leny62** [comment]
@pmuhire , kindly rebase!

**Comment by pmuhire** [comment]
Done with the tests to be reviewed and merged

**Comment by pmuhire** [comment]
> Done with the tests to be reviewed and merged

**Comment by pmuhire** [comment]
> Nice job @pmuhire , but please increase your test coverage please. Merging your PR will reduce the whole project's test coverage by a big value

Tried to add some tests, kindly review

**Review by IsiteYves — CHANGES_REQUESTED** [review]
what  about getting all ratings so that they can be displayed too and also getting them by id

**Review by pmuhire — COMMENTED** [review]
reviewed

**Review by pmuhire — COMMENTED** [review]
tests increased

**Review by IsiteYves — APPROVED** [review]
Ready for merging

**Review by leny62 — APPROVED** [review]

**Pull request merged**
