### PR TITLE
#182215527 Setup unit testing

### PR DESCRIPTION
**Pull request by kelliaUmuhire**
#### What does this PR do?
Have project testing setup
#### Description of Task to be completed?
Have the following folder structure
* `unit` -  for unit tests
* `integration` -  for integration tests
* `helper` -  for common scripts that can be reused in tests
#### How should this be manually tested?
* Clone project
* Run `npm install`
* Create a test file with format `name.test.js`
* Run `npm test`
#### What are the relevant pivotal tracker stories?
#182215527

### CODE REVIEW

**Review by IgihozoColombe — COMMENTED** [review]
Reviewed

**Review by MikeManzi — COMMENTED** [review]
Reviewed

**Review by leny62 — CHANGES_REQUESTED** [review]
Rebase with the main branch

**Review by Graziee6 — COMMENTED** [review]
Reviewed

**Comment by kelliaUmuhire** [comment]
Rebased

**Review by IsiteYves — APPROVED** [review]

**Review by leny62 — APPROVED** [review]

**Pull request merged**
